### ISSUE TITLE
能否在Msg中添加构造合并转发消息的函数？

### ISSUE THREAD

**Issue by Punizione** [ProtobufBot/pbbot-spring-boot-starter#4]
rt，mirai-core中有相应的类 `net.mamoe.mirai.message.data.ForwardMessage` 可以支持自定义合并转发消息，想问下能否以MessageChain的方式构造成一个合并转发形式，谢谢！

**Comment by lz1998** [comment]
> rt，mirai-core中有相应的类 `net.mamoe.mirai.message.data.ForwardMessage` 可以支持自定义合并转发消息，想问下能否以MessageChain的方式构造成一个合并转发形式，谢谢！

现在是基于onebot protobuf协议和QQ客户端进行通信的，暂时没有合并转发的功能，等onebot v12出来以后可能可以

**Comment by Punizione** [comment]
> > rt，mirai-core中有相应的类 `net.mamoe.mirai.message.data.ForwardMessage` 可以支持自定义合并转发消息，想问下能否以MessageChain的方式构造成一个合并转发形式，谢谢！
> 
> 现在是基于onebot protobuf协议和QQ客户端进行通信的，暂时没有合并转发的功能，等onebot v12出来以后可能可以

谢谢解答
